# Generated by Django 6.0.2 on 2026-02-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_geo_badges_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last activity timestamp', null=True),
        ),
    ]
