# Generated by Django 6.0.2 on 2026-02-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_last_seen'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text="User's country", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='countries.country'),
        ),
    ]
