# Generated by Django 6.0.2 on 2026-02-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_providerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestaireprofile',
            name='provider_type',
            field=models.CharField(choices=[('independant', 'Indépendant'), ('entreprise', 'Entreprise')], default='independant', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, help_text='Province / Region', max_length=100),
        ),
    ]
