# Generated by Django 6.0.2 on 2026-02-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_region_and_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_email_on_ad',
            field=models.BooleanField(default=False, help_text='Display email on ad pages'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone_on_ad',
            field=models.BooleanField(default=False, help_text='Display phone on ad pages'),
        ),
    ]
