# Generated by Django 6.0.2 on 2026-02-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_show_contact_on_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestaireprofile',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
