# Generated by Django 6.0.2 on 2026-02-12 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_change_website_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(help_text='Nom de la certification (ex: RGE QualiSol)', max_length=200)),
                ('license_number', models.CharField(blank=True, help_text='Numéro de licence / certificat', max_length=100)),
                ('issuing_authority', models.CharField(blank=True, help_text='Organisme émetteur', max_length=200)),
                ('expiration_date', models.DateField(blank=True, help_text="Date d'expiration", null=True)),
                ('document', models.FileField(blank=True, help_text='Document justificatif', null=True, upload_to='certifications/%Y/%m/')),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, help_text="Date de vérification par l'admin", null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes de vérification (visibles par le prestataire)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'customer_service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'prestataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='accounts.certification')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
