# Generated by Django 6.0.2 on 2026-02-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_certification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdocument',
            name='document',
            field=models.FileField(blank=True, help_text='Fichier uploadé', null=True, upload_to='documents/%Y/%m/'),
        ),
    ]
