# Generated by Django 6.0.2 on 2026-02-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code (FR, CA, BE…)', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Country name in local language', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='English name', max_length=100)),
                ('language', models.CharField(default='fr', help_text='Primary language code (fr, en)', max_length=10)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code', max_length=5)),
                ('currency_symbol', models.CharField(default='€', help_text='Symbol for display', max_length=5)),
                ('flag_emoji', models.CharField(default='🇫🇷', max_length=10)),
                ('regions', models.JSONField(blank=True, default=list, help_text='List of region/province names')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
