# Generated by Django 6.0.2 on 2026-02-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='The completed booking that entitles this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='bookings.booking'),
        ),
    ]
