# Generated by Django 6.0.2 on 2026-02-09 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom du programme d'aide", max_length=300)),
                ('provider_type', models.CharField(choices=[('government', 'Gouvernement'), ('regional', 'Collectivité régionale'), ('local', 'Collectivité locale'), ('utility', "Fournisseur d'énergie"), ('other', 'Autre')], default='government', help_text="Organisme proposant l'aide", max_length=20)),
                ('country', models.CharField(default='FR', help_text='Code pays ISO (FR, BE, CH…)', max_length=100)),
                ('region', models.CharField(blank=True, default='', help_text='Région éligible (vide = national)', max_length=200)),
                ('installation_types', models.JSONField(blank=True, default=list, help_text='Liste de types : ["solar","heat_pump","ev_charger","insulation","battery","wind"]')),
                ('property_types', models.JSONField(blank=True, default=list, help_text='Types de propriété : ["house","apartment","commercial","other"]')),
                ('income_min', models.DecimalField(blank=True, decimal_places=2, help_text='Revenu fiscal min (€/an). Vide = pas de plancher.', max_digits=12, null=True)),
                ('income_max', models.DecimalField(blank=True, decimal_places=2, help_text='Revenu fiscal max (€/an). Vide = pas de plafond.', max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text="% de réduction sur le coût d'installation", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Montant maximum de l'aide en €", max_digits=12, null=True)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'aide")),
                ('official_url', models.URLField(blank=True, help_text='Lien officiel', max_length=500)),
                ('eligibility_rules', models.JSONField(blank=True, default=dict, help_text='Règles supplémentaires (JSON libre) : ownership, age_limit, etc.')),
                ('last_verified_date', models.DateField(blank=True, help_text='Dernière date de vérification par le staff', null=True)),
                ('active', models.BooleanField(default=True, help_text='Afficher cette aide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Programme d'aide",
                'verbose_name_plural': "Programmes d'aides",
                'ordering': ['-discount_percent', '-max_amount', 'name'],
            },
        ),
    ]
