# Generated by Django 6.0.2 on 2026-02-10 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_add_blocked_and_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-priority_score', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID du message ou annonce signalé', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('message', 'Message'), ('profile', 'Profil'), ('ad', 'Annonce')], default='message', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='is_content_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_score',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('resolved', 'Résolu'), ('dismissed', 'Ignoré')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harcèlement'), ('fraud', 'Fraude'), ('inappropriate', 'Contenu inapproprié'), ('hate_speech', 'Discours haineux'), ('scam', 'Arnaque'), ('other', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('dismiss', 'Signalement ignoré'), ('delete_content', 'Contenu supprimé'), ('hide_content', 'Contenu masqué'), ('warn_user', 'Avertissement envoyé'), ('suspend_user', 'Compte suspendu'), ('ban_user', 'Compte banni'), ('unsuspend_user', 'Suspension levée')], max_length=20)),
                ('target_content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='messaging.report')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
