# Generated by Django 4.2.9 on 2026-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g. Unsplash)', max_length=500),
        ),
    ]
