# Generated by Django 6.0.2 on 2026-02-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_add_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('counter_offer', 'Contre-offre'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
