# Generated by Django 6.0.2 on 2026-02-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_add_counter_offer_status'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country where this service is offered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='countries.country'),
        ),
    ]
