# Generated by Django 6.0.2 on 2026-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_add_country_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
