# Generated by Django 6.0.2 on 2026-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix max pour fourchette (prix fixe)', max_digits=10, null=True),
        ),
    ]
