# Generated by Django 6.0.2 on 2026-02-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_add_price_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='desired_timeframe',
            field=models.CharField(blank=True, choices=[('asap', 'Le plus tôt possible'), ('3months', "D'ici 3 mois"), ('6months', "D'ici 6 mois"), ('1year', "D'ici 1 an"), ('unknown', 'Je ne sais pas')], default='unknown', max_length=20),
        ),
    ]
